export const statusList = [
  "БЕЗ СТАТУСА",
  "НУЖНО СДЕЛАТЬ",
  "В РАБОТЕ",
  "ТЕСТИРОВАНИЕ",
  "ГОТОВО",
];

export const cardList = [
  {
    id: 1,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 2,
    theme: "Research",
    title: "Название задачи",
    date: "01.11.23",
    status: "НУЖНО СДЕЛАТЬ",
  },
  {
    id: 3,
    theme: "Research",
    title: "Название задачи",
    date: "05.11.23",
    status: "В РАБОТЕ",
  },
  {
    id: 4,
    theme: "Research",
    title: "Название задачи",
    date: "10.11.23",
    status: "ТЕСТИРОВАНИЕ",
  },
  {
    id: 5,
    theme: "Research",
    title: "Название задачи",
    date: "15.11.23",
    status: "ГОТОВО",
  },
  {
    id: 6,
    theme: "Research",
    title: "Название задачи",
    date: "20.11.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 7,
    theme: "Web Design",
    title: "Название задачи",
    date: "20.11.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 8,
    theme: "Copywriting",
    title: "Название задачи",
    date: "20.11.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 9,
    theme: "Research",
    title: "Название задачи",
    date: "20.11.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 10,
    theme: "Copywriting",
    title: "Название задачи",
    date: "20.11.23",
    status: "В РАБОТЕ",
  },
  {
    id: 11,
    theme: "Web Design",
    title: "Название задачи",
    date: "20.11.23",
    status: "В РАБОТЕ",
  },
];
